### ISSUE TITLE
Set author

### ISSUE THREAD

**Issue by CodeXCad** [CodeXCad/solidworks-automator#3]
Tasks:

- [x] validate the open file
- [x] get the list of selected models
- [x] loop through each model and set the author
- [x] get the username from PDM
- [x] test what happen is PDM can't be reached ~~(copy SolidWorks and PDM DLL in project folder)~~
- [x] re-factor to have a method to get the list of selected models
- [x] re-factor in order to have this macro available as a method in other macros (method overload)

Create a method to write the current user to a file custom property.

Ideally it would:

* get the author name form the user connected to the PDM
* if the add-in can't connect to the PDM have some kind of rollback (a placeholder or reading the author name from a text file)
* set the author to a custom property on the selected files, or the open file if nothing is selected

**Comment by andrMollo** [comment]
Closed with #5
